name: FDECODE
description: "FDECODE DEVELOPED BY SYSTEMDOWN"
publish_to: "none"

version: 1.1.1+1

environment:
  sdk: ">=3.7.0-209.1.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/fdecode.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/fdecode.png"
